// <auto-generated />
using System;
using HomeInventory.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeInventory.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251120212306_UpdateLocationTracking")]
    partial class UpdateLocationTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("HomeInventory.Domain.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentLocationItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueCode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLocationItemId");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("Name");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("HomeInventory.Domain.ItemType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("ItemType");
                });

            modelBuilder.Entity("HomeInventory.Domain.LocationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocationItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedAt");

                    b.HasIndex("ItemId");

                    b.HasIndex("LocationItemId");

                    b.HasIndex("ItemId", "AddedAt");

                    b.ToTable("LocationHistory");
                });

            modelBuilder.Entity("HomeInventory.Domain.Item", b =>
                {
                    b.HasOne("HomeInventory.Domain.Item", "CurrentLocationItem")
                        .WithMany("StoredItems")
                        .HasForeignKey("CurrentLocationItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HomeInventory.Domain.ItemType", "ItemType")
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentLocationItem");

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("HomeInventory.Domain.LocationHistory", b =>
                {
                    b.HasOne("HomeInventory.Domain.Item", "Item")
                        .WithMany("LocationHistory")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeInventory.Domain.Item", "LocationItem")
                        .WithMany()
                        .HasForeignKey("LocationItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("LocationItem");
                });

            modelBuilder.Entity("HomeInventory.Domain.Item", b =>
                {
                    b.Navigation("LocationHistory");

                    b.Navigation("StoredItems");
                });
#pragma warning restore 612, 618
        }
    }
}
