// <auto-generated />
using System;
using HomeInventory.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeInventory.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521104609_AddAlertsModule")]
    partial class AddAlertsModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("HomeInventory.Domain.Entities.Alerts.AlertDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("DueTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Interval")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MonthOfYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("SourceModule", "Name")
                        .IsUnique();

                    b.ToTable("AlertDefinitions");
                });

            modelBuilder.Entity("HomeInventory.Domain.Entities.Alerts.AlertOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActiveFromUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlertDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NoticedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceModuleSnapshot")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlertDefinitionId", "PeriodKey")
                        .IsUnique();

                    b.HasIndex("AlertDefinitionId", "Status");

                    b.HasIndex("Status", "DueAtUtc");

                    b.ToTable("AlertOccurrences");
                });

            modelBuilder.Entity("HomeInventory.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NodeIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueCode")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Deleted");

                    b.HasIndex("Depth");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("Name");

                    b.HasIndex("NodeIndex");

                    b.HasIndex("ParentItemId");

                    b.HasIndex("Path");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("HomeInventory.Domain.Entities.ItemTag", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ItemTags");
                });

            modelBuilder.Entity("HomeInventory.Domain.Entities.ItemType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanContainItems")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Deleted");

                    b.HasIndex("Name");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("ItemType");
                });

            modelBuilder.Entity("HomeInventory.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Current")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocationItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedAt");

                    b.HasIndex("ItemId");

                    b.HasIndex("LocationItemId");

                    b.HasIndex("ItemId", "Current");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("HomeInventory.Domain.Entities.LocationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocationItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedAt");

                    b.HasIndex("ItemId");

                    b.HasIndex("LocationItemId");

                    b.HasIndex("ItemId", "AddedAt");

                    b.ToTable("LocationHistory");
                });

            modelBuilder.Entity("HomeInventory.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Deleted");

                    b.HasIndex("Name");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("HomeInventory.Domain.Entities.Alerts.AlertOccurrence", b =>
                {
                    b.HasOne("HomeInventory.Domain.Entities.Alerts.AlertDefinition", "AlertDefinition")
                        .WithMany("Occurrences")
                        .HasForeignKey("AlertDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertDefinition");
                });

            modelBuilder.Entity("HomeInventory.Domain.Entities.Item", b =>
                {
                    b.HasOne("HomeInventory.Domain.Entities.ItemType", "ItemType")
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeInventory.Domain.Entities.Item", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ItemType");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HomeInventory.Domain.Entities.ItemTag", b =>
                {
                    b.HasOne("HomeInventory.Domain.Entities.Item", "Item")
                        .WithMany("ItemTags")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeInventory.Domain.Entities.Tag", "Tag")
                        .WithMany("ItemTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("HomeInventory.Domain.Entities.Location", b =>
                {
                    b.HasOne("HomeInventory.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeInventory.Domain.Entities.Item", "LocationItem")
                        .WithMany()
                        .HasForeignKey("LocationItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("LocationItem");
                });

            modelBuilder.Entity("HomeInventory.Domain.Entities.LocationHistory", b =>
                {
                    b.HasOne("HomeInventory.Domain.Entities.Item", "Item")
                        .WithMany("LocationHistory")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeInventory.Domain.Entities.Item", "LocationItem")
                        .WithMany()
                        .HasForeignKey("LocationItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("LocationItem");
                });

            modelBuilder.Entity("HomeInventory.Domain.Entities.Alerts.AlertDefinition", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("HomeInventory.Domain.Entities.Item", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ItemTags");

                    b.Navigation("LocationHistory");
                });

            modelBuilder.Entity("HomeInventory.Domain.Entities.Tag", b =>
                {
                    b.Navigation("ItemTags");
                });
#pragma warning restore 612, 618
        }
    }
}
